name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
          cache: 'pip'

      - name: Update CUDA package versions
        run: |
          sed -i 's/nvidia-cublas-cu12==12.3.52/nvidia-cublas-cu12==12.3.4.1/' requirements.txt
          sed -i 's/nvidia-cuda-cupti-cu12==12.3.52/nvidia-cuda-cupti-cu12==12.3.101/' requirements.txt
          sed -i 's/nvidia-cuda-nvrtc-cu12==12.3.52/nvidia-cuda-nvrtc-cu12==12.3.103/' requirements.txt
          sed -i 's/nvidia-cuda-runtime-cu12==12.3.52/nvidia-cuda-runtime-cu12==12.3.101/' requirements.txt
          sed -i 's/nvidia-cufft-cu12==12.3.52/nvidia-cufft-cu12==12.3.100/' requirements.txt
          sed -i 's/nvidia-curand-cu12==12.3.52/nvidia-curand-cu12==12.3.101/' requirements.txt
          sed -i 's/nvidia-cusolver-cu12==12.3.52/nvidia-cusolver-cu12==12.3.100/' requirements.txt
          sed -i 's/nvidia-cusparse-cu12==12.3.52/nvidia-cusparse-cu12==12.3.100/' requirements.txt
          sed -i 's/nvidia-nccl-cu12==12.3.52/nvidia-nccl-cu12==2.19.3/' requirements.txt
          sed -i 's/nvidia-nvtx-cu12==12.3.52/nvidia-nvtx-cu12==12.3.101/' requirements.txt
          cat requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: education/autograding@v1