name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
          cache: 'pip'

      - name: Update dependencies versions
        run: |
          cat > requirements.txt << EOL
          colorama==0.4.3
          hypothesis==6.54.0
          numpy>=2.0.0  # Latest version with Python 3.12 support
          pre-commit==2.20.0
          pytest==8.0.0  # Latest version for Python 3.12
          pytest-env
          pytest-runner==5.3.1
          typing_extensions>=4.0.0
          pyright==1.1.376
          EOL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: education/autograding@v1